version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
      - echo changing directory
artifacts:
  files:
    - target/student-app.jar
  discard-paths: yes