version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
      - echo changing directory
      - cd ./target
      - ls -l
artifacts:
  files:
    - ./target/student-app.jar
  discard-paths: yes